### ISSUE TITLE
[Cliente] Quando edito um cliente, o ERP não vem preenchido

### ISSUE THREAD

**Issue by dn32** [dn32/front#33]
![image](https://user-images.githubusercontent.com/12012626/77781888-179d8c00-7035-11ea-989d-0012828ebc3e.png)

**Comment by BrenoCabral** [comment]
Cliente não tem ERP. Só versão. Esse controle aí é pra poder trazer as versões do ERP.

**Comment by dn32** [comment]
> Cliente não tem ERP. Só versão. Esse controle aí é pra poder trazer as versões do ERP.

Você pode pegar o ERP de Cliente.VersaoDeErp.Erp

**Comment by BrenoCabral** [comment]
Blz
